[tool.poetry]
name = "src"
version = "0.3.0"
description = ""
authors = ["kondou <kondou@localdomain>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.3.1"
dacite = "^1.9.2"


[tool.poetry.group.dev.dependencies]
black = "^26.3.1"
isort = "^8.0.1"
mypy = "^1.19.1"
pylint = "^4.0.5"
pytest = "^9.0.2"
pytest-cov = "^7.0.0"
pytest-mock = "^3.15.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
#mh_summary = "src/mh_summary.py"
#csv_preprocessor = "src.csv_preprocessor:cli" # clickの入口
#mh_summary = "src.main:main"

[tool.black]
line_length = 120

[tool.pytest.ini_options]
testpaths = ["tests",]
